<?php

/**
 * MyBB related stuff
 * needed for successful test results
 */
define("IN_MYBB", 1);
class pluginTest {
    public function add_hook($string, $string) {
        return true;
    }
}
$plugins = new pluginTest();
require_once realpath(dirname(__FILE__)) . '/../source/inc/plugins/liste.php';

/**
 * Test class for ShowDates.
 * Generated by PHPUnit on 2012-01-07
 */
class ShowDatesTest extends PHPUnit_Framework_TestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public static function setUpBeforeClass()
    {
        error_reporting(E_ALL | E_STRICT);
        ini_set('display_startup_errors', 1);
        ini_set('display_errors', 1);
        date_default_timezone_set('Europe/Berlin');
    }

    protected function setUp()
    {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * testCheckFutureDate()
     */
    public function testCheckFutureDateTrue()
    {
        $result = ShowDates::checkFutureDate(time() + 1000, time());
        $this->assertTrue($result);
        $result = ShowDates::checkFutureDate(time()+1, time());
        $this->assertTrue($result);
    }
    
    /**
     * testCheckFutureDate()
     */
    public function testCheckFutureDateFalse()
    {
        $result = ShowDates::checkFutureDate(time() + 1000, time()+5000);
        $this->assertFalse($result);
        $result = ShowDates::checkFutureDate(time(), time()+1);
        $this->assertFalse($result);
    }

}
